/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.cloudflare.Worker"
      "url": string
    }
    "BetterAuthSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "D1Token": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Database": {
      "type": "sst.cloudflare.D1"
    }
    "DatabaseCredentials": {
      "accountId": string
      "id": string
      "type": "sst.sst.Linkable"
    }
    "Urls": {
      "api": string
      "auth": string
      "site": string
      "type": "sst.sst.Linkable"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}