/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

import "sst"
declare module "sst" {
  export interface Resource {
    "BetterAuthSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "D1Token": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DatabaseCredentials": {
      "accountId": string
      "id": string
      "type": "sst.sst.Linkable"
    }
    "Urls": {
      "api": string
      "auth": string
      "site": string
      "type": "sst.sst.Linkable"
    }
  }
}
// cloudflare 
import * as cloudflare from "@cloudflare/workers-types";
declare module "sst" {
  export interface Resource {
    "Api": cloudflare.Service
    "Database": cloudflare.D1Database
  }
}

import "sst"
export {}